### ISSUE TITLE
Ошибка при загрузке плагина

### ISSUE THREAD

**Issue by Remint32** [KeviTV/Matrix-plugin#3]
Последний серверный билд 104.7, при загрузке вылетает ошибка:
![image](https://user-images.githubusercontent.com/13190430/79714170-a6ba5e80-82d8-11ea-9c01-20815bff6902.png)

**Comment by Remint32** [comment]
Вызывается принудительной загрузкой и парсингом данных Discord-бота.
Нужно добавить опциональность и параметр в конфиг.

**Comment by Fatonndev** [comment]
Данная ошибка вылелатает из-за неверного токена. Добавлена возможность отключать бота.
